CREATE TABLE `ZERO_BASE_CUSTOMER` (
    `ID` varchar(64) NOT NULL,
    `NAME` varchar(64) DEFAULT NULL,
    `SEX` smallint DEFAULT NULL COMMENT '0-男1-女2-未知',
    `ID_CARD` varchar(32) DEFAULT NULL,
    `TELEPHONE` varchar(20) DEFAULT NULL,
    `EMAIL` varchar(32) DEFAULT NULL,
    `PHOTO` varchar(255) DEFAULT NULL,
    `REMARK` varchar(255) DEFAULT NULL,
    `CREATE_TIME` bigint DEFAULT NULL,
    `UPDATE_TIME` bigint DEFAULT NULL,
     PRIMARY KEY (`ID`),
     KEY `IDX_ZERO_BASE_CUSTOMER_02` (`ID_CARD`),
     KEY `IDX_ZERO_BASE_CUSTOMER_01` (`NAME`,`TELEPHONE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户表';